{{- if .Values.keelson.namespaces }}
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Keelson contributors (Fred Cooke)

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}.{{ include "keelson.fullname" . }}
  labels:
    {{- include "keelson.labels" . | nindent 4 }}
    kaptain.org/project-name: keelson
    kaptain.org/version: "1.25"
    kaptain.org/owner: keelson-pro
  annotations:
    kaptain.org/source-repository: keelson-pro/keelson
subjects:
  - kind: ServiceAccount
    name: {{ include "keelson.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}.{{ include "keelson.fullname" . }}
{{- end }}
