# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Keelson contributors (Fred Cooke)

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keelson.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keelson.labels" . | nindent 4 }}
    kaptain.org/project-name: keelson
    kaptain.org/version: "1.24"
    kaptain.org/owner: keelson-pro
  annotations:
    kaptain.org/source-repository: keelson-pro/keelson
rules:
  # State ConfigMap (keelson-state) and central config ConfigMaps (keelson-registries, keelson-notifications)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "patch", "update"]
